import bcrypt from "bcryptjs/dist/bcrypt.js";

const data = {
    users:[
        {
            name:'Admin',
            email:'admin@admin.ru',
            password: bcrypt.hashSync('admin',8),
            isAdmin: true,
        },
        {
            name:'TestUser',
            email:'testuser@testuser.ru',
            password: bcrypt.hashSync('testuser',8),
            isAdmin: false,
        },
    ],
    product:[
        {
            name:'Отрио, таблетки 10мг 30шт',
            category:'Лекарство',
            image:'/images/otrio.png',
            price:200,
            countInStock:10,
            brand:'Акрихин',
            rating:4.5,
            numReviews:40,           
            description:'Средство для нормализации обмена веществ',
        },
        {
            name:'Ксалатан, капли глазные 0,005 % 2,5 мл 1 шт',
            category:'Лекарство',
            image:'/images/ksalatan.png',
            price:521,
            countInStock:20,
            brand:'Пфайзер',
            rating:4,
            numReviews:3,
            description:'Лекарство при глакуоме',
        },
        {
            name:'Гепон лиофилизат 2 мг флакон, 1 шт',
            category:'Лекарство',
            image:'/images/gepon.png',
            price:2117,
            countInStock:0,
            brand:'Иммафарма',
            rating:2.5,
            numReviews:4,
            description:'Иммуностимулятор',
        },
        {
            name:'Цефтриаксон флакон 1 г',
            category:'Лекарство',
            image:'/images/ceftriakson.png',
            price:16,
            countInStock:1,
            brand:'Рафарма',
            rating:4,
            numReviews:10,
            description:'Антибиотик',
        },
        {
            name:'Вилдегра таблетки пролонг. 100 мг, 10 шт.',
            category:'Лекарство',
            image:'/images/vildegra.png',
            price:970,
            countInStock:99,
            brand:'Озон',
            rating:4,
            numReviews:5,
            description:'Лекарства для терапии импотенции у мужчин ',
        },
        {
            name:'Дерматикс гель силиконовый для предотвращения образования рубцов, 15 г',
            category:'Лекарство',
            image:'/images/dermatiks.png',
            price:50,
            countInStock:123,
            brand:'Хансон Медикал',
            rating:4.6,
            numReviews:33,
            description:'Средство для лечения кожи ',
        },
        {
            name:'Продукт 7',
            category:'Лекарство',
            image:'/images/gepon.png',
            price:7,
            countInStock:0,
            brand:'Иммафарма',
            rating:2.5,
            numReviews:4,
            description:'Иммуностимулятор',
        },
        {
            name:'Продукт 8',
            category:'Лекарство',
            image:'/images/ceftriakson.png',
            price:8,
            countInStock:1,
            brand:'Рафарма',
            rating:4,
            numReviews:10,
            description:'Антибиотик',
        },
        {
            name:'Продукт 9',
            category:'Лекарство',
            image:'/images/vildegra.png',
            price:9,
            countInStock:99,
            brand:'Озон',
            rating:4,
            numReviews:5,
            description:'Лекарства для терапии импотенции у мужчин ',
        },
        {
            name:'Продукт 10',
            category:'Лекарство',
            image:'/images/dermatiks.png',
            price:10,
            countInStock:123,
            brand:'Хансон Медикал',
            rating:4.6,
            numReviews:33,
            description:'Средство для лечения кожи ',
        }
        
    ]
};

export default data;