const data = {
    product:[
        {
            _id:'1',
            name:'Отрио, таблетки 10мг 30шт',
            categofy:'Лекарство',
            image:'/images/otrio.png',
            price:200,
            countInStock:10,
            brand:'Акрихин',
            rating:4.5,
            numReviews:40,           
            description:'Средство для нормализации обмена веществ',
        },
        {
            _id:'2',
            name:'Ксалатан, капли глазные 0,005 % 2,5 мл 1 шт',
            categofy:'Лекарство',
            image:'/images/ksalatan.png',
            price:521,
            countInStock:20,
            brand:'Пфайзер',
            rating:4,
            numReviews:3,
            description:'Лекарство при глакуоме',
        },
        {
            _id:'3',
            name:'Гепон лиофилизат 2 мг флакон, 1 шт',
            categofy:'Лекарство',
            image:'/images/gepon.png',
            price:2117,
            countInStock:0,
            brand:'Иммафарма',
            rating:2.5,
            numReviews:4,
            description:'Иммуностимулятор',
        },
        {
            _id:'4',
            name:'Цефтриаксон флакон 1 г',
            categofy:'Лекарство',
            image:'/images/ceftriakson.png',
            price:16,
            countInStock:1,
            brand:'Рафарма',
            rating:4,
            numReviews:10,
            description:'Антибиотик',
        },
        {
            _id:'5',
            name:'Вилдегра таблетки пролонг. 100 мг, 10 шт.',
            categofy:'Лекарство',
            image:'/images/vildegra.png',
            price:970,
            countInStock:99,
            brand:'Озон',
            rating:4,
            numReviews:5,
            description:'Лекарства для терапии импотенции у мужчин ',
        },
        {
            _id:'6',
            name:'Дерматикс гель силиконовый для предотвращения образования рубцов, 15 г',
            categofy:'Лекарство',
            image:'/images/dermatiks.png',
            price:50,
            countInStock:123,
            brand:'Хансон Медикал',
            rating:4.6,
            numReviews:33,
            description:'Средство для лечения кожи ',
        },
        {
            _id:'7',
            name:'Продукт 7',
            categofy:'Лекарство',
            image:'/images/gepon.png',
            price:7,
            countInStock:0,
            brand:'Иммафарма',
            rating:2.5,
            numReviews:4,
            description:'Иммуностимулятор',
        },
        {
            _id:'8',
            name:'Продукт 8',
            categofy:'Лекарство',
            image:'/images/ceftriakson.png',
            price:8,
            countInStock:1,
            brand:'Рафарма',
            rating:4,
            numReviews:10,
            description:'Антибиотик',
        },
        {
            _id:'9',
            name:'Продукт 9',
            categofy:'Лекарство',
            image:'/images/vildegra.png',
            price:9,
            countInStock:99,
            brand:'Озон',
            rating:4,
            numReviews:5,
            description:'Лекарства для терапии импотенции у мужчин ',
        },
        {
            _id:'10',
            name:'Продукт 10',
            categofy:'Лекарство',
            image:'/images/dermatiks.png',
            price:10,
            countInStock:123,
            brand:'Хансон Медикал',
            rating:4.6,
            numReviews:33,
            description:'Средство для лечения кожи ',
        }
        
    ]
};

export default data;