export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

export const PRODUCT_CATEGORY_DETAILS_REQUEST = 'PRODUCT_CATEGORY_DETAILS_REQUEST';
export const PRODUCT_CATEGORY_DETAILS_SUCCESS = 'PRODUCT_CATEGORY_DETAILS_SUCCESS';
export const PRODUCT_CATEGORY_DETAILS_FAIL = 'PRODUCT_CATEGORY_DETAILS_FAIL';
export const PRODUCT_CATEGORY_DETAILS_RESET = 'PRODUCT_CATEGORY_DETAILS_RESET';

export const PRODUCT_CATEGORY_CREATE_REQUEST = 'PRODUCT_CATEGORY_CREATE_REQUEST';
export const PRODUCT_CATEGORY_CREATE_SUCCESS = 'PRODUCT_CATEGORY_CREATE_SUCCESS';
export const PRODUCT_CATEGORY_CREATE_FAIL = 'PRODUCT_CATEGORY_CREATE_FAIL';
export const PRODUCT_CATEGORY_CREATE_RESET = 'PRODUCT_CATEGORY_CREATE_RESET';

export const PRODUCT_CATEGORY_DELETE_REQUEST = 'PRODUCT_CATEGORY_DELETE_REQUEST';
export const PRODUCT_CATEGORY_DELETE_SUCCESS = 'PRODUCT_CATEGORY_DELETE_SUCCESS';
export const PRODUCT_CATEGORY_DELETE_FAIL = 'PRODUCT_CATEGORY_DELETE_FAIL';
export const PRODUCT_CATEGORY_DELETE_RESET = 'PRODUCT_CATEGORY_DELETE_RESET';

export const PRODUCT_CATEGORY_UPDATE_REQUEST = 'PRODUCT_CATEGORY_UPDATE_REQUEST';
export const PRODUCT_CATEGORY_UPDATE_SUCCESS = 'PRODUCT_CATEGORY_UPDATE_SUCCESS';
export const PRODUCT_CATEGORY_UPDATE_FAIL = 'PRODUCT_CATEGORY_UPDATE_FAIL';
export const PRODUCT_CATEGORY_UPDATE_RESET = 'PRODUCT_CATEGORY_UPDATE_RESET';

export const PRODUCT_PROVIDER_LIST_REQUEST = 'PRODUCT_PROVIDER_LIST_REQUEST';
export const PRODUCT_PROVIDER_LIST_SUCCESS = 'PRODUCT_PROVIDER_LIST_SUCCESS';
export const PRODUCT_PROVIDER_LIST_FAIL = 'PRODUCT_PROVIDER_LIST_FAIL';

export const PRODUCT_PROVIDER_DETAILS_REQUEST = 'PRODUCT_PROVIDER_DETAILS_REQUEST';
export const PRODUCT_PROVIDER_DETAILS_SUCCESS = 'PRODUCT_PROVIDER_DETAILS_SUCCESS';
export const PRODUCT_PROVIDER_DETAILS_FAIL = 'PRODUCT_PROVIDER_DETAILS_FAIL';
export const PRODUCT_PROVIDER_DETAILS_RESET = 'PRODUCT_PROVIDER_DETAILS_RESET';

export const PRODUCT_PROVIDER_CREATE_REQUEST = 'PRODUCT_PROVIDER_CREATE_REQUEST';
export const PRODUCT_PROVIDER_CREATE_SUCCESS = 'PRODUCT_PROVIDER_CREATE_SUCCESS';
export const PRODUCT_PROVIDER_CREATE_FAIL = 'PRODUCT_PROVIDER_CREATES_FAIL';
export const PRODUCT_PROVIDER_CREATE_RESET = 'PRODUCT_PROVIDER_CREATE_RESET';

export const PRODUCT_PROVIDER_UPDATE_REQUEST = 'PRODUCT_PROVIDER_UPDATE_REQUEST';
export const PRODUCT_PROVIDER_UPDATE_SUCCESS = 'PRODUCT_PROVIDER_UPDATE_SUCCESS';
export const PRODUCT_PROVIDER_UPDATE_FAIL = 'PRODUCT_PROVIDER_UPDATE_FAIL';
export const PRODUCT_PROVIDER_UPDATE_RESET = 'PRODUCT_PROVIDER_UPDATE_RESET';

export const PRODUCT_PROVIDER_DELETE_REQUEST = 'PRODUCT_PROVIDER_DELETE_REQUEST';
export const PRODUCT_PROVIDER_DELETE_SUCCESS = 'PRODUCT_PROVIDER_DELETE_SUCCESS';
export const PRODUCT_PROVIDER_DELETE_FAIL = 'PRODUCT_PROVIDER_DELETE_FAIL';
export const PRODUCT_PROVIDER_DELETE_RESET = 'PRODUCT_PROVIDER_DELETE_RESET';


export const PRODUCT_FORMRELEASE_LIST_REQUEST = 'PRODUCT_FORMRELEASE_LIST_REQUEST';
export const PRODUCT_FORMRELEASE_LIST_SUCCESS = 'PRODUCT_FORMRELEASE_LIST_SUCCESS';
export const PRODUCT_FORMRELEASE_LIST_FAIL = 'PRODUCT_FORMRELEASE_LIST_FAIL';

export const PRODUCT_FORMRELEASE_DETAILS_REQUEST = 'PRODUCT_FORMRELEASE_DETAILS_REQUEST';
export const PRODUCT_FORMRELEASE_DETAILS_SUCCESS = 'PRODUCT_FORMRELEASE_DETAILS_SUCCESS';
export const PRODUCT_FORMRELEASE_DETAILS_FAIL = 'PRODUCT_FORMRELEASE_DETAILS_FAIL';
export const PRODUCT_FORMRELEASE_DETAILS_RESET = 'PRODUCT_FORMRELEASE_DETAILS_RESET';

export const PRODUCT_FORMRELEASE_CREATE_REQUEST = 'PRODUCT_FORMRELEASE_CREATE_REQUEST';
export const PRODUCT_FORMRELEASE_CREATE_SUCCESS = 'PRODUCT_FORMRELEASE_CREATE_SUCCESS';
export const PRODUCT_FORMRELEASE_CREATE_FAIL = 'PRODUCT_FORMRELEASE_CREATE_FAIL';
export const PRODUCT_FORMRELEASE_CREATE_RESET = 'PRODUCT_FORMRELEASE_CREATE_RESET';


export const PRODUCT_FORMRELEASE_UPDATE_REQUEST = 'PRODUCT_FORMRELEASE_UPDATE_REQUEST';
export const PRODUCT_FORMRELEASE_UPDATE_SUCCESS = 'PRODUCT_FORMRELEASE_UPDATE_SUCCESS';
export const PRODUCT_FORMRELEASE_UPDATE_FAIL = 'PRODUCT_FORMRELEASE_UPDATE_FAIL';
export const PRODUCT_FORMRELEASE_UPDATE_RESET = 'PRODUCT_FORMRELEASE_UPDATE_RESET';

export const PRODUCT_FORMRELEASE_DELETE_REQUEST = 'PRODUCT_FORMRELEASE_DELETE_REQUEST';
export const PRODUCT_FORMRELEASE_DELETE_SUCCESS = 'PRODUCT_FORMRELEASE_DELETE_SUCCESS';
export const PRODUCT_FORMRELEASE_DELETE_FAIL = 'PRODUCT_FORMRELEASE_DELETE_FAIL';
export const PRODUCT_FORMRELEASE_DELETE_RESET = 'PRODUCT_FORMRELEASE_DELETE_RESET';

export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST';
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS';
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';

